# 데이터 전처리  
    * 클래스 별로 폴더 생성해서 사전에 이미지 분류
    
      | Accessories
        | 12345.jpg
        | 34564.jpg
      | Apparel
        | 45685.jpg
        | 21475.jpg ...

## 1. 판다스 모듈을 활용하여 csv파일 읽기

In [2]:
import torch
import pandas as pd
import os
import numpy as np

In [3]:
data_path = "./archive/myntradataset/"
print(os.listdir(data_path))

['images', 'styles.csv', 'train']


In [4]:
df = pd.read_csv(data_path + "styles.csv", error_bad_lines=False)

b'Skipping line 6044: expected 10 fields, saw 11\nSkipping line 6569: expected 10 fields, saw 11\nSkipping line 7399: expected 10 fields, saw 11\nSkipping line 7939: expected 10 fields, saw 11\nSkipping line 9026: expected 10 fields, saw 11\nSkipping line 10264: expected 10 fields, saw 11\nSkipping line 10427: expected 10 fields, saw 11\nSkipping line 10905: expected 10 fields, saw 11\nSkipping line 11373: expected 10 fields, saw 11\nSkipping line 11945: expected 10 fields, saw 11\nSkipping line 14112: expected 10 fields, saw 11\nSkipping line 14532: expected 10 fields, saw 11\nSkipping line 15076: expected 10 fields, saw 12\nSkipping line 29906: expected 10 fields, saw 11\nSkipping line 31625: expected 10 fields, saw 11\nSkipping line 33020: expected 10 fields, saw 11\nSkipping line 35748: expected 10 fields, saw 11\nSkipping line 35962: expected 10 fields, saw 11\nSkipping line 37770: expected 10 fields, saw 11\nSkipping line 38105: expected 10 fields, saw 11\nSkipping line 38275: ex

## 2. 이미지명이 담긴 Image 속성 추가 ex) 12345.jpg

In [5]:
df['image'] = df.apply(lambda row: str(row['id']) + ".jpg", axis=1) #image명이 담긴 image 속성 추가
df.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName      image  
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt  15970.jpg  
1  2012.0  Casual             Peter England Men Party Blue Jeans  39386.jpg  
2  2016.0  Casual                       Titan Women Silver Watch  59263.jpg  
3  2011.0  Casual  Manchester United Men Solid Black Track Pants  21379.jpg  
4  2012.0  Casual                          Puma Men Grey T-shirt  53759.jpg

## 3. 데이터의 라벨 값과 이미지명 속성을 따로 저장

In [6]:
data_label = df.iloc[:,2] #데이터의 라벨 저장

In [7]:
print(type(data_label))
print(data_label)
print(len(data_label))

<class 'pandas.core.series.Series'>
0              Apparel
1              Apparel
2          Accessories
3              Apparel
4              Apparel
             ...      
44419         Footwear
44420         Footwear
44421          Apparel
44422    Personal Care
44423      Accessories
Name: masterCategory, Length: 44424, dtype: object
44424


In [8]:
data_image_idx = df.iloc[:,10]

In [9]:
print(type(data_image_idx))
print(data_image_idx)
print(len(data_image_idx))

<class 'pandas.core.series.Series'>
0        15970.jpg
1        39386.jpg
2        59263.jpg
3        21379.jpg
4        53759.jpg
           ...    
44419    17036.jpg
44420     6461.jpg
44421    18842.jpg
44422    46694.jpg
44423    51623.jpg
Name: image, Length: 44424, dtype: object
44424


In [15]:
print(data_image_idx[76])
print(data_label[76])

54118.jpg
Footwear


## 4. 이미지명과 라벨 값을 이용해 class 별로 폴더 내에 이미지 저장

In [10]:
import cv2

In [11]:
img = cv2.imread("./archive/myntradataset/images/"+"1163.jpg",0)
print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [19]:
for i in range(len(data_label)):
    image_dir = "./archive/myntradataset/images/"+data_image_idx[i]
    img = cv2.imread(image_dir, cv2.IMREAD_COLOR) # 이미지 불러오기

    save_dir = "./archive/myntradataset/pre_data/train/"+data_label[i]+"/"+data_image_idx[i]
    cv2.imwrite(save_dir,img)